# Generated by Django 4.0.1 on 2022-01-27 18:07

from django.db import migrations, models
import django.db.models.deletion
import yt_dl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Video_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to=yt_dl.models.upload_file_path)),
                ('youtube_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yt_dl.youtube_post')),
            ],
        ),
    ]
