# Generated by Django 4.0.1 on 2022-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_dl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_post',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
